import Head from 'next/head'
import Image from 'next/image'
// import Map from './components/map'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic"

export default function Home() {

  const MapWithNoSSR = dynamic (() => import("../pages/components/map"), {
    ssr: false
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Flights Overhead</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <MapWithNoSSR />
      </main>  
    </div>
  )
}
